test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,6 +10,7 @@ variables: &global_variables
   stage: build
   image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
   before_script:
+    - apk update
     - apk add zip
   script:
     - "dotnet publish -r win-x64 -c Release -o publish /p:PublishSingleFile=true"
@@ -147,30 +148,13 @@ release:
     - |
       # Verify artifacts
       #
-      apk update
-      apk add grep
       VERSION=${CI_COMMIT_TAG:1}
-      echo version=$VERSION
-      echo list contents
-      ls -1
-      echo -----
-      # touch injector-$VERSION.win64.zip
-      echo "injector-$VERSION.*.zip"
-      ls -1 >contents
-      grep --help
-      grep 'zip' contents
-      echo hello world
-      ls -1 | grep -m 1 zip
-      echo boom time
-      ARCHIVE_NAME=$(ls -1 | grep -m1 "injector-$VERSION.*.zip")
-      echo 0000000
-      echo $ARCHIVE_NAME
-      echo 0000000
+      ARCHIVE_NAME=$(ls -1 | grep -m1 injector-$VERSION.*.zip || true)
       if [ ! -f "$ARCHIVE_NAME" ]; then
-        echo $ARCHIVE_NAME missing
+        ls -1
+        echo "injector-$VERSION.*.zip missing"
         return 1
       fi
-      echo DEFAULT
       return 1
     - apk add jq curl
   variables: &deploy_variables
